### ISSUE TITLE
Why API 15?

### ISSUE THREAD

**Issue by ppamorim** [Alexrs95/RecyclerViewRenderers#1]

**Comment by alexrs** [comment]
I know that RecyclerView works in lower versions, but acording to the [Android Developers website](https://developer.android.com/about/dashboards/index.html) below Android 4.0.3 there are only a 7% of the devices, and this percentage will decrease in the following months. The main reason is that is time for android:minSdkVerson="15".

**Comment by ppamorim** [comment]
@Alexrs95 In Brazil and another developing countries, is remarkable a lot of users using older versions of Android.
If there isn't technical reason for the lock, is needless to try to force the developer up the version of the API. I myself only copied the classes and added it on my application...

**Comment by ppamorim** [comment]
@Alexrs95 ???

**Comment by alexrs** [comment]
@ppamorim I will try to test it in a device with an older version of Android and if everything works as expected, I will upload a new version with a lower minSdkVersion.
